# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Newsboard' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Newsboard
   pod ‘Firebase’
   pod ‘Firebase/Core’
   pod ‘Firebase/Auth’
   pod ‘Firebase/Database’
   pod 'Firebase/Storage'
   pod 'JSQMessagesViewController'

  target 'NewsboardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewsboardUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
